input {
  tcp {
    port => 50000
    codec => json_lines
  }
}

filter {
  mutate {
    add_tag => [ "qdefense-microservices" ]
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "qdefense-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
